load persons from postgres to index persons
nikitaKunevich/ETL_sprint_2.5 pull request #1
Opened 2021-02-10 07:49 UTC by InnokentyDM

Добавил новый индекс и etl процесс для обновления этого индекса

2021-02-10 18:42 UTC, nikitaKunevich requested changes
@InnokentyDM 
Все хорошо, только посмотри, пожалуйста комент по поводу

2021-02-10 18:42 UTC, nikitaKunevich commented on postgres_to_es/daemon.py
> +class PersonElastic(BaseModel):
Важно: Посмотри страницу "техническое задание на второй модуль".
[link](https://praktikum.yandex.ru/learn/middle-python/courses/c3542626-7807-4495-b198-555e60bfd8a6/sprints/3019/topics/8485aa46-19dd-46d0-ac31-0494ce8aada2/lessons/901374b5-f63d-4ab8-83d2-263b42ba42ab/)

Структура ответа содержить роль человека:
{
  "uuid": "uuid",
  "full_name": "str",
  "role": "str",
  "film_ids": ["uuid"]
},

2021-02-10 18:42 UTC, nikitaKunevich commented on postgres_to_es/daemon.py
> +def get_updated_postgres_entries(table: str, pg_url: str, target, state: State,
Можно лучше: Лучше бы убрать форматирование либо в отдельный комит, если оно необходимо , чтобы было понятно, где функциональные изменения.
Либо убрать изменение форматирования вовсе, если предыдущий код не противоречил код-стайлу

2021-02-10 18:42 UTC, nikitaKunevich commented on es.persons.schema.json
> +      "filmwork_titles": {
Смотри ниже по структуре, кажется, она нужна несколько иной.

2021-02-10 18:42 UTC, nikitaKunevich commented on postgres_to_es/daemon.py
>      """Отправляет в target id фильмов, полученных пересечением входящих id с записями в join_table по join_field."""
Стоит исправить: Раз изменил функцию, то докстринг тоже поменяй, чтобы отражал изменения.

2021-02-10 18:42 UTC, nikitaKunevich commented on postgres_to_es/daemon.py
> +def transform_persons_data(target):
Придирка: Если сделал transform_persons_data, то старый метод transform можно переименовать.

2021-02-11 07:34 UTC, nikitaKunevich commented on postgres_to_es/daemon.py
> +    last_id = state.state_get_key(f'{table}.{es_index}.last_id', str(uuid.UUID(int=0)))
❗️БАГ, надо исправить: посмотри — etl в бесконечный цикл уходит, думаю проблема из-за использования одного ключа для состояния для persons и для фильмов.
updated_at и last_id постоянно переписываются разными процессами.
Полагаю, что можно решить, если только один раз вызывать get_updated_postgres_entries для каждой таблицы, можно и иначе, но надо думать.

2021-02-11 07:35 UTC, nikitaKunevich requested changes
Нашел баг. ETL бесконечно обновляет es

2021-02-11 16:42 UTC, meshchaninov approved these changes

2021-02-11 21:23 UTC, merged